name = "edith-medical"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 : remplacer par vos valeurs (voir CLOUDFLARE_SETUP.md)
# Token API : ne pas mettre en clair ici â†’ utiliser "wrangler secret put CLOUDFLARE_API_TOKEN"
[vars]
CLOUDFLARE_ACCOUNT_ID = "777ec3364551bfb4fa3a5b54982affa3"
CLOUDFLARE_D1_DATABASE_ID = "1e779961-6b12-4df6-b722-280522403252"

# [[d1_databases]]
# binding = "DB"
# database_name = "edith-blog"
# database_id = "1e779961-6b12-4df6-b722-280522403252"
